language: scala

script: sbt ++$TRAVIS_SCALA_VERSION test scripted

after_script:
  - if [[ $TRAVIS_TEST_RESULT == 0 && 
          "$TRAVIS_REPO_SLUG" == "scoverage/sbt-scoverage" &&
          "$TRAVIS_BRANCH" == "master" ]]; then sbt "^publish"; fi

scala:
  - "2.10.4"
